package org.umlproject.UI;

import javafx.scene.SnapshotParameters;
import javafx.scene.control.Alert;
import javafx.scene.image.WritableImage;
import javafx.scene.layout.Pane;
import javafx.embed.swing.SwingFXUtils;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;

import java.io.File;
import java.io.IOException;
import javafx.scene.paint.Color;
import javafx.scene.transform.Transform;
import org.umlproject.DiagramElementListener;
import org.umlproject.DocumentState;
import org.umlproject.UMLDocument;

/**
 * Concrete command class within the Command design pattern. This class implements the exportCommand interface
 * by defining the execute method. This object, once created by the client (the exportScreenshotMenuAction method
 * in GuiController) will be passed to the invoker class which will call the execute() method on it.
 */
public class ScreenshotCommand implements ExportCommand {
    //world is the receiver in the Command design pattern
    Pane world;
    File saveLocation;

    public ScreenshotCommand(File saveLocation, Pane world){
        if(saveLocation == null || world == null){
            throw new IllegalArgumentException("One or more of the arguments are null");
        }
        this.world = world;
        this.saveLocation = saveLocation;
    }

    /**
     * Implementation of the ExportCommand interface's execute() method. Will generate a png image
     * and save it to the user designated saveLocation.
     * @throws IOException which may result from the ImageIO.write() call.
     */
    public void execute() throws IOException {
        SnapshotParameters snapshotParameters = new SnapshotParameters();
        snapshotParameters.setFill(GuiColor.WORLD_BACKGROUND_COLOR);
        snapshotParameters.setTransform(Transform.scale(4,4));
        
        //Hide buttons and selection
        GuiSelect.getInstance().resetSelect();
        
        for(DiagramElementListener element :UMLDocument.getInstance().getUIListeners())
        {
            if(element instanceof GuiClass guiClass)
            {
                guiClass.formatForScreenshot();
            }
        }
        
        //Convert World to WriteableImage object.
        WritableImage fxImage = world.snapshot(snapshotParameters, null);
        //Convert WriteableImage object into a BufferedImage so it can be saved as a "png".
        BufferedImage awtImage = ScreenshotCommand.toBufferedImage(fxImage);
        //Save image as a png in the given file location.
        ImageIO.write(awtImage, "png", saveLocation);
        
        //Return scene to normal
        GuiController.getInstance().redrawAllElements();
    }

    /**
     * Helper method for execute(). Used to convert the fxImage generated by snapshot() into a
     * BufferedImage which is what ImageIO.write() accepts as an argument.
     * @param fxImage, the image to be converted.
     * @return BufferedImage object that fxImage was converted into.
     */
    public static BufferedImage toBufferedImage(WritableImage fxImage){
        return SwingFXUtils.fromFXImage(fxImage, null);
    }
}
