package org.umlproject;

import java.util.Objects;
import javafx.geometry.Point2D;
import javafx.geometry.Rectangle2D;
import static org.umlproject.RelationshipType.OTHER;

public class UMLRelationship  extends UMLDiagramElement implements Cloneable
{
    private String sourceName;
    private String destinationName;
    private RelationshipType relationshipType;
    private String customNameType;
    
    //-------------------------------- Main class -----------------------------------
    public UMLRelationship(String sourceName, String destinationName, RelationshipType relationshipType, String customNameType)
    {
        this(sourceName, destinationName, relationshipType);
        if (this.relationshipType == RelationshipType.OTHER) 
        {
            if(customNameType == null || customNameType.isEmpty()) throw new IllegalArgumentException("Custom name is required for OTHER data type");
            
            this.customNameType = customNameType;
        }
        else
            this.customNameType = null;
    }
    public UMLRelationship(String sourceName, String destinationName, RelationshipType relationshipType)
    {
        this.sourceName = sourceName;
        this.destinationName = destinationName;
        this.relationshipType = relationshipType;
    }
    /**
     *
     * @return the source UMLClass.
     */
    public UMLClass getSource(){
        String sourceName = getSourceName();
        UMLDocument doc = UMLDocument.getInstance();
        return doc.getClass(sourceName);
    }
    /**
     *
     * @return the destination UMLClass.
     */
    public UMLClass getDestination(){
        String destinationName = getDestinationName();
        UMLDocument doc = UMLDocument.getInstance();
        return doc.getClass(destinationName);
    }
    /**
     * @return the source name
     */
    public String getSourceName()
    {
        return this.sourceName;
    }
    /**
     * @return the destination name
     */
    public String getDestinationName()
    {
        return this.destinationName;
    }
    /**
     * @return the relationship type
     */
    public RelationshipType getRelationshipType(){
        return this.relationshipType;
    }
    /**
     * @return NULL or the custom name
     */
    public String getCustomNameType(){
        return this.customNameType;
    }
    /**
     * @return The relationship name as a string with support for custom names.
     */
    public String getRelationshipName()
    {
        if(this.relationshipType == OTHER)
            return getCustomNameType();
        
        return this.relationshipType.toString();
    }
    /**
     * Sets a new source name, calls to update listener
     * @param newName The new source name
     */
    public void setSourceName(String newName)
    {
        this.sourceName = newName;
        updateListener(true);
    }
    /**
     * Calls the update destination name, calls to update listener
     * @param newName The new destination name
     */
    public void setDestinationName(String newName)
    {
        this.destinationName = newName;
        updateListener(true);
    }
    /**
     * Sets the relationship type, calls to update listener
     * @param newType The new type.
     */
    public void setRelationshipType(RelationshipType newType){
        this.relationshipType = newType;
        updateListener(true);
    }
    /**
     * Sets the relationship type, calls to update listener
     * Automatically assigns relationshipType to OTHER, enforcing a new custom relationship
     * @param newTypeCustom The new type.
     */
    public void setCustomNameType(String newTypeCustom){
        this.relationshipType = OTHER;
        this.customNameType = newTypeCustom;
        updateListener(true);
    }
    @Override
    public String toString() {
        if(this.relationshipType.equals(RelationshipType.OTHER)) return String.format("%s -> %s : %s", sourceName, destinationName, this.customNameType);
        return String.format("%s -> %s : %s", sourceName, destinationName, this.relationshipType);
    }
    @Override
    public boolean equals(Object  obj) 
    {
        if(this == obj) 
            return true;
        if(obj == null || getClass() != obj.getClass()) 
            return false;
        
        UMLRelationship castedObject = (UMLRelationship)obj;
        //Bare bones implementation.
        //TODO: When you add more to the class, maintain this equals function.
        return castedObject.sourceName.equals(this.sourceName) && castedObject.destinationName.equals(this.destinationName)
                && castedObject.customNameType.equals(this.customNameType);
    }

    @Override
    public int hashCode(){
        //IDE autogenerated code...
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.sourceName);
        hash = 29 * hash + Objects.hashCode(this.destinationName);
        hash = 29 * hash + Objects.hashCode(this.customNameType);
        return hash;
    }
    
    @Override
    public UMLRelationship clone()
    {
        return UMLDocument.executeActionUnderState(DocumentState.CLONING, ()-> {
            UMLRelationship relationship = this.relationshipType == RelationshipType.OTHER ?
                    new UMLRelationship(sourceName, destinationName, relationshipType, customNameType) :
                    new UMLRelationship(sourceName, destinationName, relationshipType);
            relationship.setListener(this.listener);
            relationship.networkId = this.networkId;
            return relationship;
        });
    }
}
