package org.umlproject;

import java.util.Objects;

public class UMLRelationship 
{
    private String sourceName;
    private String destinationName;
    public UMLRelationship(String sourceName, String destinationName)
    {
        this.sourceName = sourceName;
        this.destinationName = destinationName;
    }
    public String getSourceName()
    {
        return this.sourceName;
    }
    public String getDestinationName()
    {
        return this.destinationName;
    }
    public void setDestinationName(String newName)
    {
        this.destinationName = newName;
    }
    public void setSourceName(String newName)
    {
        this.sourceName = newName;
    }
    @Override
    public String toString() {
        return String.format("%s -> %s", sourceName, destinationName);
    }
    @Override
    public boolean equals(Object  obj) 
    {
        if(this == obj) 
            return true;
        if(obj == null || getClass() != obj.getClass()) 
            return false;
        
        UMLRelationship castedObject = (UMLRelationship)obj;
        //Bare bones implementation.
        //TODO: When you add more to the class, maintain this equals function.
        return castedObject.sourceName.equals(this.sourceName) && castedObject.destinationName.equals(this.destinationName);
    }

    @Override
    public int hashCode(){
        //IDE autogenerated code...
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.sourceName);
        hash = 29 * hash + Objects.hashCode(this.destinationName);
        return hash;
    }
}
