package org.umlproject;

import java.util.Objects;
import javafx.geometry.Point2D;
import javafx.geometry.Rectangle2D;

public class UMLRelationship  extends UMLDiagramElement
{
    private String sourceName;
    private String destinationName;
    
    //-------------------------------- UMLSelectable Interface -----------------------------------
    /**
     * A line cannot contain a point simply. So how will users click on it?
     * The user will have a 'forgiveness' radius, we then check if the line intersects the 'forgiveness circle'
     * 
     */
    @Override
    public boolean contains(Point2D selectionPoint) {
        final float forgivenessRadius = 5;
        //Something like this: Idk figure it out.
        //https://www.geeksforgeeks.org/dsa/check-line-touches-intersects-circle/
        return false;
    }
    /**
     * 
     */
    @Override
    public boolean intersects(Rectangle2D selectionRectangle) {
        
        return false;
    }
    //-------------------------------- Main class -----------------------------------
    public UMLRelationship(String sourceName, String destinationName)
    {
        this.sourceName = sourceName;
        this.destinationName = destinationName;
    }
    public String getSourceName()
    {
        return this.sourceName;
    }
    public String getDestinationName()
    {
        return this.destinationName;
    }
    public void setDestinationName(String newName)
    {
        this.destinationName = newName;
    }
    public void setSourceName(String newName)
    {
        this.sourceName = newName;
    }
    @Override
    public String toString() {
        return String.format("%s -> %s", sourceName, destinationName);
    }
    @Override
    public boolean equals(Object  obj) 
    {
        if(this == obj) 
            return true;
        if(obj == null || getClass() != obj.getClass()) 
            return false;
        
        UMLRelationship castedObject = (UMLRelationship)obj;
        //Bare bones implementation.
        //TODO: When you add more to the class, maintain this equals function.
        return castedObject.sourceName.equals(this.sourceName) && castedObject.destinationName.equals(this.destinationName);
    }

    @Override
    public int hashCode(){
        //IDE autogenerated code...
        int hash = 7;
        hash = 29 * hash + Objects.hashCode(this.sourceName);
        hash = 29 * hash + Objects.hashCode(this.destinationName);
        return hash;
    }
}
